url: "https://sebastian-zm.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/javascript-objetuak" # the subpath of your site, e.g. /blog
title: "javascript objetuak" # the name of your site, e.g. ACME Corp.
lang: "eu"

exclude:
  - Gemfile
  - Gemfile.lock